version: '3'

services:
  postgres:
    image: 'postgres:16.2-alpine3.19'
    container_name: 'java-postgres'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=java'