version: '3'

services:
  db:
    image: 'postgres:16.2-alpine3.19'
    container_name: 'db'
    ports:
      - '5000:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=md5'
      - 'POSTGRES_DB=creditCalculator'